### ISSUE TITLE
Test4 analysis_step

### ISSUE THREAD

**Issue by CharlesJB** [CharlesJB/test#19]
S'assurer que toute l'information de la table `analysis_step` est extraite correctement.
Pour plus de détails, voir la fonction [`prepareENCODEdb`](https://github.com/CharlesJB/ENCODExplorer/blob/master/R/prepare_data.R#L68-L133).
# TODO:
- [ ] Analyser le JSON
- [ ] Updater [`clean_table`](https://github.com/CharlesJB/ENCODExplorer/blob/master/R/rest_api.R#L41-L134)
- [ ] Ajouter les tests unitaires (au besoin)
