### ISSUE TITLE
Test5 access_key

### ISSUE THREAD

**Issue by CharlesJB** [CharlesJB/test#20]
S'assurer que toute l'information de la table [`access_key`](https://github.com/ENCODE-DCC/encoded/blob/master/src/encoded/schemas/access_key.json) est extraite correctement.
Pour plus de détails, voir la fonction [`prepareENCODEdb`](https://github.com/CharlesJB/ENCODExplorer/blob/master/R/prepare_data.R#L68-L133).
# TODO:
- [ ] Analyser le JSON
- [ ] Updater [`clean_table`](https://github.com/CharlesJB/ENCODExplorer/blob/master/R/rest_api.R#L41-L134)
- [ ] Ajouter les tests unitaires (au besoin)
