### ISSUE TITLE
Valider table: hotspot_quality_metric

### ISSUE THREAD

**Issue by CharlesJB** [CharlesJB/test#54]
S'assurer que toute l'information de la table [`hotspot_quality_metric`](https://github.com/ENCODE-DCC/encoded/blob/master/src/encoded/schemas/hotspot_quality_metric.json) est extraite correctement.
Pour plus de détails, voir la fonction [`prepareENCODEdb`](https://github.com/CharlesJB/ENCODExplorer/blob/master/R/prepare_data.R#L68-L133).
# TODO:
- [ ] Analyser le JSON
- [ ] Updater [`clean_table`](https://github.com/CharlesJB/ENCODExplorer/blob/master/R/rest_api.R#L41-L134)
- [ ] Ajouter les tests unitaires (au besoin)
